### ISSUE TITLE
Resetting the question counter

### ISSUE THREAD

**Issue by nilsjha** [Z1MM32M4N/latex-homework-class#6]
Dear jez,

Is it possible to reset the counter for the `\question`-blocks in the middle of the document ?
As for example in use with assignments with multiple parts:

 * Part 1
    1. Question 1
    1. Question 2
    1. Question n
 * Part 2
    1. Question 1
    1. Question 2
    1. Question n

I tried to invoke `\setcounter` in the middle of the document, but then LaTeX throws a ``no-counter error`.

Anyways, thanks for creating this wonderful class, it has so far simplified my workflow, and been very useful!

Kind regards,
nilsjha

### Example code
```
\part{Part 1}
\question
This is Question 1
\begin{verbatim}
\end{verbatim}
\part{Part 2}
\setcounter{\questionCounter}{<1>}
\question
This should be Question 1, but is Question 2
```
#### Error message

```
153 error| Undefined control sequence. c@\questionCounter
153 error| Undefined control sequence.
153 error| LaTeX Error: No counter '' defined.
```

**Comment by jez** [comment]
Don't put the `\`. Just:

```latex
\setcounter{questionCounter}{0}
```

Also you want to set it to 0 not 1. The counter is incremented before rendering the question number text, not after it:

https://github.com/jez/latex-homework-class/blob/master/homework.cls#L74
